name: Lint & Tests
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          make install
          make build
        env:
          CI: true
      - name: Run Linter & Tests
        run: |
          make lint
      - name: Tests
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_COVERAGE }}
        with:
          coverageCommand: make tests
          debug: true